### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by gitforwebwork** [hassifow/Slack.API-User.info#1]
Hi,
could you document how this is implemented/used please? I am pretty sure this is what I need, I just don't know how to make use of it from my Dialogflow Agent.

**Comment by hassifow** [comment]
Hi, 

In your DialogFlow agent make an intent, for example, call it 'Welcome'. Then in your lambda function or whatever codebase you are using call it like this using a switch statement:

```                   case "Welcome":
                           getUsername(userid).then((output) => {
                                 callback(null, {"fulfillmentText": `Greetings, *${output.user.profile.first_name}*. How can I help you?`});
                        });
                   break;
```
